### ISSUE TITLE
Russian locale isn't working properly, invisible characters

### ISSUE THREAD

**Issue by Meister1593** [elisescu/tty-share#20] opened 2020-10-30 06:45 UTC
**Issue:**
Writing russian locale (`ru_RU.UTF-8`) through browser terminal makes characters weird question marks at sharing computer end and invisible characters in browser client end.
Also, there's issue with erasing bash prompt in remote tty (at sharing computer end), because i write invisible characters (most likely tty-share doesn't expect these characters to be not shown, so it counts them too)

**System:**
Arch Linux with `linux-lts 5.4.72-1` kernel
Using `xfce4-terminal 0.8.9.2-2` with `tty-share 0.6.1` from [AUR](https://aur.archlinux.org/packages/tty-share/)

Issue shown in gif bellow
![Peek 2020-10-30 10-23](https://user-images.githubusercontent.com/7141787/97668091-acb8a580-1a9a-11eb-907a-ea699a484b86.gif)

**Comment by elisescu** [comment] 2020-12-20 09:07
Could you try with the latest version and see if the issue is still there? I updated the xterm.js to a newer version and maybe they fixed that on their side.
Tbh, I don't even know how to fix it I am sure it's possible, just my frontend skills are very very basic. But I hope to get some time one day to look into it, if the latest version still has the issue.

**Comment by Meister1593** [comment] 2020-12-28 14:48
I checked with latest available version (`2.1.0`) and it's indeed working now
I can type Russian in both terminals and it will look fine on both sides.
I guess this can be closed now

**Comment by elisescu** [comment] 2020-12-28 16:48
Cool. Closing it then :)

**Closed by elisescu** 2020-12-28 16:48 UTC
